swagger: '2.0'  # Spécifie la version de Swagger utilisée.
info:
  title: Documentation de l'API Bank Argent  # Titre de la documentation de l'API.
  description: Contient tous les points d'accès API disponibles dans cette base de code  # Description de l'API.
  version: '2.1.0'  # Version de l'API.
  termsOfService: 'http://swagger.io/terms/'  # URL des conditions d'utilisation de l'API.
host: localhost:3001  # Hôte où l'API est hébergée.
basePath: /api/v1  # Chemin de base pour tous les points d'accès de l'API.
schemes:
  - http  # Schéma de transfert utilisé (ici HTTP).
paths:
  /user/login:  # Point d'accès pour la connexion de l'utilisateur.
    post:  # Méthode HTTP utilisée (POST).
      tags:
        - Module Utilisateur  # Tag pour regrouper les points d'accès liés aux utilisateurs.
      summary: Connexion  # Résumé du point d'accès.
      description: API pour la connexion  # Description du point d'accès.
      parameters:
        - in: body  # Le paramètre est dans le corps de la requête.
          name: body
          description: Charge utile de connexion  # Description du paramètre.
          required: true  # Indique que ce paramètre est obligatoire.
          schema:
            $ref: '#/definitions/Login'  # Référence à la définition du schéma Login.
      produces:
        - application/json  # Format de réponse produit.
      responses:
        '200':  # Code de statut HTTP pour une réponse réussie.
          description: Connexion réussie  # Description de la réponse.
          schema:
            $ref: '#/definitions/LoginResponse'  # Référence à la définition du schéma LoginResponse.
        '400':
          description: Champs invalides  # Description de la réponse pour un champ invalide.
        '500':
          description: Erreur interne du serveur  # Description de la réponse pour une erreur interne.

  /user/signup:  # Point d'accès pour l'inscription de l'utilisateur.
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour l'inscription
      parameters:
        - in: body
          name: body
          description: Charge utile d'inscription
          required: true
          schema:
            $ref: '#/definitions/User'  # Référence à la définition du schéma User.
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'  # Référence à la définition du schéma ApiResponse.
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /user/profile:  # Point d'accès pour gérer le profil de l'utilisateur.
    post:
      security:
        - Bearer: []  # Sécurité avec un token Bearer.
      tags:
        - Module Utilisateur
      summary: Récupérer le profil utilisateur
      description: API pour récupérer un profil utilisateur
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: Mettre à jour le profil utilisateur
      description: API pour mettre à jour un profil utilisateur
      parameters:
        - in: body
          name: body
          description: Mettre à jour les attributs du profil utilisateur
          required: true
          schema:
            $ref: '#/definitions/UserProfile'  # Référence à la définition du schéma UserProfile.
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /transactions:  # Point d'accès pour obtenir toutes les transactions.
    get:
      security:
        - Bearer: []
      tags:
        - Module Transactions
      summary: Obtenir toutes les transactions du mois en cours groupées par compte
      description: Récupérer toutes les transactions du mois en cours, groupées par compte
      produces:
        - application/json
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionGroupedByAccount'  # Référence à la définition du schéma TransactionGroupedByAccount.
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur

  /transactions/{transactionId}:  # Point d'accès pour obtenir les détails d'une transaction spécifique.
    get:
      security:
        - Bearer: []
      tags:
        - Module Transactions
      summary: Obtenir les détails d'une transaction spécifique
      description: Récupérer des informations détaillées sur une transaction spécifique
      parameters:
        - in: path
          name: transactionId
          required: true
          description: ID de la transaction à récupérer
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'  # Référence à la définition du schéma TransactionDetails.
        '400':
          description: Champs invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
    put:
      security:
        - Bearer: []
      tags:
        - Module Transactions
      summary: Mettre à jour la transaction
      description: Mettre à jour les détails d'une transaction spécifique
      parameters:
        - in: path
          name: transactionId
          required: true
          description:  indentifiant de la transaction à mettre à jour
          type: string
        - in: body
          name: body
          description: Informations mises à jour sur la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionInfo'  # Référence à la définition du schéma TransactionInfo.
      produces:
        - application/json
      responses:
        '200':
          description: Informations de la transaction mises à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

definitions:  # Définition des schémas utilisés dans les paramètres et les réponses.
  User:
    type: object
    properties:
      email:
        type: string
        description: Email de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
      firstName:
        type: string
        description: Prénom de l'utilisateur
      lastName:
        type: string
        description: Nom de famille de l'utilisateur
      userName:
        type: string
        description: Nom public de l'utilisateur

  Login:
    type: object
    properties:
      email:
        type: string
        description: Email pour la connexion
      password:
        type: string
        description: Mot de passe pour la connexion

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          accountId:
            type: string
          date:
            type: string
            format: date
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
          transactionType:
            type: string
          category:
            type: string
          note:
            type: string  

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant de la transaction
      accountId:
        type: string
        description: Identifiant du compte
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: double
        description: Montant de la transaction
      balance:
        type: number
        description: Solde du compte après la transaction
      transactionType:
        type: string
        description: Type de la transaction (e.g., débit, crédit)
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Note sur la transaction
      
  TransactionDetails:
    type: object
    properties:
      accountId:
        type: string
        description: ID du compte associé à la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        description: Montant de la transaction
      balance:
        type: number
        description: Solde du compte après la transaction
      transactionType:
        type: string
        description: Type de la transaction (e.g., débit, crédit)
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Note sur la transaction

  TransactionInfo:
    type: object
    properties:
      id:
        type: string
        description: Identifiant de la transaction
      accountId:
        type: string
        description: Identifiant du compte
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        description: Montant de la transaction
      balance:
        type: number
        description: Solde du compte après la transaction
      transactionType:
        type: string
        description: Type de la transaction (e.g., débit, crédit)
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Note sur la transaction

  TransactionGroupedByAccount:
    type: object
    properties:
      accountId:
        type: string
        description: Identifiant du compte
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
securityDefinitions:  # Définition des schémas de sécurité.
  Bearer:
    type: apiKey
    name: Authorization
    in: header  # Le token Bearer doit être envoyé dans l'en-tête de la requête.
